on:
  push:
    branches:
      - 'main'
      
jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        # Check if a file under actions/ or with the Dockerfile has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^actions/' -or $_ -match 'Dockerfile' }
        $HasDiff = $SourceDiff.Length -gt 0

        # Set the output named "actions_changed"
        Write-Host "::set-output name=actions_changed::$HasDiff"

    # Run the step only with "actions_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.actions_changed == 'True'
      run: echo would run our Rasa action push action here...